#spring:
#  profiles:
#    active: eureka1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: false
  server:
    enable-self-preservation: false #开发环境下关闭，生产环境注掉
spring:
  application:
    name: eureka
server:
  port: 8761